name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout patch repository
        uses: actions/checkout@v4

      - name: Upstream patch
        run: |
          chmod +x scripts/*.sh

          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          ./scripts/bootstrap.sh


      - name: Launching the original release flow
        uses: workspace/upstream/.github/workflows/release.yml
          with:
            release-version: ${{ github.ref_name }}
